apiVersion: v1
kind: PersistentVolume
metadata:
  name: $GCE_DISK
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    pdName: $GCE_DISK
